[package]
name = "api-rust-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.6.20", features = ["headers", "json", "tracing"] }
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.4.0", features = [
    "trace",
    "compression-br",
    "propagate-header",
    "sensitive-headers",
    "cors",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "1.0"
validator = { version = "0.16", features = ["derive"] }
config = "0.13"
lazy_static = "1.4"
sqlx = { version = "0.7.2", features = ["postgres", "runtime-tokio-native-tls"] }
serde = { version = "1.0", features = ["derive"] }
hyper = { version = "0.14", features = ["full"] }

[dev-dependencies]
assert-json-diff = "2.0.2"
reqwest = { version = "0.11.18", features = ["json"] }
pretty_assertions = "1.4.0"

