services:
  develop_api:
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@develop_db:5432"
      RUN_MODE: develop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - develop_db

  develop_db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: develop_db
    ports:
      - "5430:5432"
    volumes:
      - develop_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d develop_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  develop_db:
