version: '3'
services:
  develop_api:
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@develop_db:5432"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - develop_db
  develop_db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RUN_MODE: development
    ports:
      - "5430:5432"
    volumes:
      - develop_db:/var/lib/postgresql/data

volumes:
  develop_db: