version: '3'
services:
  test_api:
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@test_db:5432"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - test_db

  test_db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RUN_MODE: tests
    ports:
      - "5431:5432"
    volumes:
      - test_db:/var/lib/postgresql/data

volumes:
  test_db:
    driver: local