services:
  develop_db:
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - ".env.develop"
    environment:
      RUN_MODE: development
    ports:
      - "5430:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
