environment="development"

[auth]
secret="secret"

[logger]
level = "debug"
sql_explain = "debug"

[database]
uri="postgres://postgres:password@localhost:54322/db"
password="password"

[server]
port=3000