environment="development"

[auth]
secret="secret"

[logger]
level="debug"
sql_explain="debug"

[database]
uri="postgres://postgres:password@localhost:5430/develop_db"
max_connections=5
password="password"

[server]
port=3000