environment="development"

[auth]
secret="secret"

[logger]
level="debug"
sql_explain="true"

[database]
uri="postgres://postgres:password@localhost:5431/test_db"
max_connections=5
password="password"

[server]
port=3000